version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes: ["mongodata:/data/db"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  nats:
    image: nats:2.10
    command: ["-js","-sd","/data"]
    ports: ["4222:4222","8222:8222"]
    volumes: ["natsdata:/data"]
volumes: { pgdata: {}, mongodata: {}, natsdata: {} }
