version: '3.8'
services:
  identity-service:
    build:
      context: .
      dockerfile: apps/identity-service/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgresql://shubham:shubham@localhost:5432/devbhoomi_one?schema=identity
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=devbhoomi_one
      - POSTGRES_USER=shubham
      - POSTGRES_PASSWORD=shubham
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
